development:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      # hosts:
      #   - localhost:27017
      # database: weather_db
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: weather_test
  options:
    raise_not_found_error: false
